# Site Info
title:              "Xiaoran Jia"
description:        "PhD Candidate in Accouunting"
author_name:        "Xiaoran Jia" # change this to your name
logo_url:           https://github.com/jiastargrass/stargrasspics/blob/master/img/profile_pic.jpg?raw=true # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://jiastargrass.github.io/  # main url
baseurl:
permalink:           # Post permalink
timezone:           America/Toronto # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
